version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  # Configure version updates
  # Patch versions will be auto-merged when CI passes
  # Minor and major versions will require review
  versioning-strategy: auto
  # Enable auto-merge for patch updates only
  # This requires GitHub Actions workflow to handle the auto-merge
  labels:
    - "dependencies"
    - "automerge"
  commit-message:
    prefix: "deps"
    include: "scope"
